### ISSUE TITLE
RPC workqueue exceeded

### ISSUE THREAD

**Issue by SmartArray** [SmartArray/digibyte-rosetta-server#2]
Sync fails with:

```
{ Error: Bitcoin JSON-RPC: Work queue depth exceeded
    at IncomingMessage.<anonymous> (/root/rosetta-node/node_modules/bitcoind-rpc/lib/index.js:115:29)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  cause:
   { Error: Bitcoin JSON-RPC: Work queue depth exceeded
       at IncomingMessage.<anonymous> (/root/rosetta-node/node_modules/bitcoind-rpc/lib/index.js:115:29)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 429 },
  isOperational: true,
  code: 429 }
{ error:
   { Error: Timeout of 5000ms exceeded
       at RequestBase._timeoutError (/root/rosetta-node/node_modules/superagent/lib/request-base.js:613:13)
       at Timeout.<anonymous> (/root/rosetta-node/node_modules/superagent/lib/request-base.js:628:12)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10)
     timeout: 5000,
     code: 'ECONNABORTED',
     errno: 'ETIME',
     response: undefined } }
(node:42) UnhandledPromiseRejectionWarning: SyncerError: Unable to sync to 1536: undefined
    at RosettaSyncer.sync (/root/rosetta-node/node_modules/rosetta-node-sdk/lib/syncer/index.js:266:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:42) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Submitted by Josiah Spackman_

**Comment by SmartArray** [comment]
Increased workqueue depth in generated digibyte.conf: https://github.com/SmartArray/digibyte-rosetta-server/commit/fd550e001fe760cae2ccdd26fc7281b06517d34c

This should make the issue disappear.
